---
- name: Configure access | Add a new user named devops
  user:
    name: cinarra
    shell: /bin/bash
    password: "{{ cinarra_password }}"

- name: Configure access | Add devops user to the sudoers
  copy:
    dest: "/etc/sudoers.d/cinarra"
    content: "cinarra  ALL=(ALL)  NOPASSWD: ALL"

- name: Configure access | Deploy SSH Key
  authorized_key: 
    user: cinarra
    key: "{{ lookup('file', 'roles/files/cinarra.pub') }}"
    state: present