---
#- name: EC2
- hosts: local
  connection: local
  become: no
#  block:
  include_tasks: "ec2.yml"
#  environment: "{{ property_env }}"

#- name: Install Jenkins
#  hosts: ec2host
#  tasks:
#    - "install-{{ ansible_distribution | lower }}.yml"
#  environment: "{{ property_env }}"