---
- name: Configure nginx proxy | Configure nginx.repo
  copy:
    src: files/nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0644

- name: Configure nginx proxy | Import nginx key
  rpm_key:
    state: present
    key: https://nginx.org/keys/nginx_signing.key

- name: Configure nginx proxy | Install nginx
  yum:
    name: nginx
    state: present

- name: Configure nginx proxy | Copy nginx config to /etc
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0640
  notify: nginx_reload

- name: Configure nginx proxy | Copy proxy config to /etc
  template:
    src: templates/jenkins.conf.j2
    dest: /etc/nginx/conf.d/jenkins.conf
    owner: root
    group: root
    mode: 0640
  notify: nginx_reload

- name: Configure nginx proxy | Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: true