---

- name: EC2 | Start an instance, add EBS
  ec2_instance:
    name: "jenkins-nginx-instance"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    image_id: ami-00138b07206d4ceaf
    vpc_subnet_id: subnet-19486f63
    region: us-east-2
    instance_type: t2.micro
    key_name: jenkins
    security_group: "launch-wizard-1"
    wait: true
    volumes:
      - device_name: /dev/sda1
        ebs:
          volume_size: 29
          delete_on_termination: true
  register: ec2_result

- debug: var=ec2_result.instances[0].public_dns_name

- name: EC2 | Add new host to hosts
  add_host:
    hostname: "{{ ec2_result.instances[0].public_ip_address }}"
    groupname: ec2host
    dnsname: "{{ ec2_result.instances[0].public_dns_name }}"

- name: EC2 | Save DNS for another play
  add_host:
    name: EC2HOST
    groupname: extvars
    dnsname: "{{ ec2_result.instances[0].public_dns_name }}"

- name: EC2 | Wait for instances to listen on port:22
  wait_for:
    state: started
    host: "{{ ec2_result.instances[0].public_dns_name }}"
    port: 22